baseURL = "/"
languageCode = "fr"
DefaultContentLanguage = "fr" # on règle le langage sur français
title = "Mes ressources"
theme = "mainroad"
enableEmoji = true

[Author]
  name = "Germain SIPIERE"
  bio = "Germain SIPIERE, formateur en conception et développement d'applications à l'AFPA. J'utilise différentes technologies et j'adore en découvrir continuellement de nouvelles"
  avatar = "img/moi.jpg"

[markup.goldmark.renderer]
unsafe= true

[Params]
  subtitle = "Site de partage de ressources" # Subtitle of your site. Used in site header
  description = "Site personnel de Germain SIPIERE de partage de ressources" # Site description. Used in meta description
  copyright = "Germain SIPIERE" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "02-01-2006" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "#e22d30" # Override highlight color
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files


[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget


[Params.widgets.social]
  # Enable parts of social widget
  # facebook = "username"
  # twitter = "username"
  # instagram = "username"
  linkedin = "gsipiere"
  # telegram = "username"
  github = "germainsip"
  # gitlab = "username"
  # bitbucket = "username"
  email = "gsipiere@gmail.com"

